// Generated by CodiumAI

import { fireEvent, render } from '@testing-library/react';
import CheckBoxField from '.';

describe('code snippet', () => {
  // Renders a checkbox input with a label
  it('should render a checkbox input with a label', () => {
    const { getByLabelText } = render(<CheckBoxField label="Test Label" />);
    const checkboxInput = getByLabelText('Test Label');

    expect(checkboxInput).toBeInTheDocument();
  });

  // Checkbox is unchecked by default
  it('should have an unchecked checkbox by default', () => {
    const { getByLabelText } = render(<CheckBoxField label="Test Label" />);
    const checkboxInput = getByLabelText('Test Label');

    expect(checkboxInput).not.toBeChecked();
  });

  // Clicking on the label toggles the checkbox
  it('should toggle the checkbox when the label is clicked', () => {
    const { getByLabelText } = render(<CheckBoxField label="Test Label" />);
    const checkboxInput = getByLabelText('Test Label');

    fireEvent.click(checkboxInput);
    expect(checkboxInput).toBeChecked();

    fireEvent.click(checkboxInput);
    expect(checkboxInput).not.toBeChecked();
  });
});
