name: build

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependecies
        run: npm ci -f
      - name: Format Check
        run: npm run prettier
      - name: Linter Check
        run: npm run lint
      